version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker_data/mongodb:/data/db
    # networks:
    #   - backend

  backend:
    container_name: backend-test
    image: backend
    profiles:
      - backend
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UID
        - GID
        - USER_NAME
        - POETRY_VERSION
        - APP_PORT
        - BUILD_TARGET
    restart: always
    env_file:
      - ./envs/.env
    volumes:
      - ./src:/home/${USER_NAME}/app
    ports:
      - "8080:8080"
      - "5678:5678"